# Generated by Django 6.1.2 on 2026-10-08 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(unique=True, validators=[django.core.validators.RegexValidator(message='Enter one uppercase letter followed by one or more digits.', regex='^[A-Z][0-9]+$')])),
                ('booking_status', models.BooleanField(default=False)),
            ],
        ),
    ]
