# Generated by Django 6.1.2 on 2026-10-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ("-booking_date", "-id")},
        ),
    ]
